const assert = require("node:assert/strict"); const { spawn } = require("node:child_process"); const { once } = require("node:events"); const path = require("node:path"); const test = require("node:test"); const { Client } = require("pg");
const shouldRun = process.env.RUN_DB_TESTS === "1"; const port = Number(process.env.TEST_EMERGENCY_API_PORT || 5009); const baseUrl = `http://127.0.0.1:${port}`;
const request = async (pathname, options = {}) => { const response = await fetch(`${baseUrl}${pathname}`, options); return { response, body: await response.json() }; };
test("emergency incidents are recipient-scoped, idempotent, and staff-managed", { skip: !shouldRun }, async (t) => {
  const server = spawn(process.execPath, ["index.js"], { cwd: path.join(__dirname, ".."), env: { ...process.env, PORT: String(port) }, stdio: "ignore" }); const client = new Client({ host: process.env.DB_HOST, port: Number(process.env.DB_PORT), user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME });
  t.after(async () => { server.kill(); await once(server, "exit"); await client.end(); }); await client.connect(); for (let i=0;i<50;i+=1) { try { if ((await fetch(`${baseUrl}/api/db-test`)).ok) break; } catch (_) {} await new Promise((r)=>setTimeout(r,100)); }
  async function user(name,email,role="student") { const r=await request("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password:"integration-password"})}); assert.equal(r.response.status,200); if(role!=="student"){await client.query("UPDATE users SET role=$1 WHERE id=$2",[role,r.body.user.id]);const l=await request("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password:"integration-password"})});r.body.token=l.body.token;}return {user:r.body.user,headers:{"Content-Type":"application/json",Authorization:`Bearer ${r.body.token}`}}; }
  const owner=await user("Emergency Owner","emergency.owner@test","owner"), warden=await user("Emergency Warden","emergency.warden@test","warden"), student=await user("Emergency Student","emergency.student@test"), parent=await user("Emergency Parent","emergency.parent@test","parent"), outsider=await user("Emergency Outsider","emergency.outsider@test","parent");
  const hostel=await request("/api/owner/hostels",{method:"POST",headers:owner.headers,body:JSON.stringify({name:"Emergency Hostel",address:"Road",city:"Lahore",total_capacity:2})}); const booking=await request("/api/bookings",{method:"POST",headers:student.headers,body:JSON.stringify({hostel_id:hostel.body.hostel.id,check_in:"2036-01-10",check_out:"2036-01-20",status:"pending"})}); await request(`/api/owner/bookings/${booking.body.booking.id}`,{method:"PATCH",headers:owner.headers,body:JSON.stringify({status:"confirmed"})}); await request("/api/owner/wardens",{method:"POST",headers:owner.headers,body:JSON.stringify({hostel_id:hostel.body.hostel.id,email:warden.user.email})});
  const invite=await request("/api/student/parents/invitations",{method:"POST",headers:student.headers,body:JSON.stringify({email:parent.user.email})}); await request("/api/parent/invitations/accept",{method:"POST",headers:parent.headers,body:JSON.stringify({token:invite.body.test_invitation_token})});
  const alertHeaders={...student.headers,"idempotency-key":"emergency-test-001"}; const incident=await request("/api/emergencies",{method:"POST",headers:alertHeaders,body:JSON.stringify({alert_type:"medical",description:"Integration emergency",latitude:31.5,longitude:74.3})}); assert.equal(incident.response.status,201); const duplicate=await request("/api/emergencies",{method:"POST",headers:alertHeaders,body:JSON.stringify({alert_type:"medical"})}); assert.equal(duplicate.body.duplicate,true);
  const parentView=await request(`/api/parent/children/${student.user.id}/emergencies`,{headers:parent.headers}); assert.equal(parentView.body.incidents[0].id,incident.body.incident.id); const denied=await request(`/api/parent/children/${student.user.id}/emergencies`,{headers:outsider.headers}); assert.equal(denied.response.status,404);
  const staffUpdate=await request(`/api/emergencies/${incident.body.incident.id}`,{method:"PATCH",headers:warden.headers,body:JSON.stringify({status:"acknowledged"})}); assert.equal(staffUpdate.response.status,200,JSON.stringify(staffUpdate.body)); const resolved=await request(`/api/emergencies/${incident.body.incident.id}`,{method:"PATCH",headers:owner.headers,body:JSON.stringify({status:"resolved",reason:"Handled"})}); assert.equal(resolved.body.incident.status,"resolved");
});
