BEGIN;

ALTER TABLE hostels ADD COLUMN IF NOT EXISTS university VARCHAR(150);
ALTER TABLE hostels ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 8);
ALTER TABLE hostels ADD COLUMN IF NOT EXISTS longitude NUMERIC(11, 8);

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY,
  hostel_id INTEGER NOT NULL REFERENCES hostels(id) ON DELETE CASCADE,
  room_number VARCHAR(20) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  available_capacity INTEGER NOT NULL CHECK (available_capacity >= 0),
  room_type VARCHAR(20) NOT NULL DEFAULT 'shared',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (hostel_id, room_number)
);

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS favorites (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hostel_id INTEGER NOT NULL REFERENCES hostels(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, hostel_id)
);

COMMIT;