function registerMessagingRoutes({ app,pool,requireAuth,requireRole,isValidInt,ownerHasHostel,wardenHasHostel }) {
  async function activeLink(parentId,studentId){const r=await pool.query("SELECT 1 FROM parent_student_links WHERE parent_user_id=$1 AND student_user_id=$2 AND status='active'",[parentId,studentId]);return r.rowCount>0}
  async function participant(conversationId,user){const r=await pool.query("SELECT * FROM conversations WHERE id=$1",[conversationId]);if(!r.rowCount)return null;const c=r.rows[0];if([c.parent_user_id,c.student_user_id,c.staff_user_id].includes(user.id))return c;return null}
  app.post("/api/parent/conversations",requireAuth,requireRole("parent"),async(req,res)=>{const studentId=Number(req.body.student_id),type=String(req.body.type||"parent_student"),staffId=Number(req.body.staff_user_id);if(!isValidInt(studentId)||!await activeLink(req.user.id,studentId))return res.status(404).json({error:"Linked student not found"});if(!["parent_student","parent_staff"].includes(type))return res.status(400).json({error:"Invalid conversation type"});let hostelId=null;if(type==="parent_staff"){if(!isValidInt(staffId))return res.status(400).json({error:"staff_user_id is required"});const b=await pool.query("SELECT hostel_id FROM bookings WHERE user_id=$1 AND status IN ('pending','confirmed') ORDER BY created_at DESC LIMIT 1",[studentId]);if(!b.rowCount)return res.status(409).json({error:"Student has no active hostel booking"});hostelId=b.rows[0].hostel_id;const staff=await pool.query("SELECT role FROM users WHERE id=$1",[staffId]);const allowed=staff.rowCount&&(staff.rows[0].role==='owner'?await ownerHasHostel(pool,staffId,hostelId):staff.rows[0].role==='warden'?await wardenHasHostel(pool,staffId,hostelId):false);if(!allowed)return res.status(404).json({error:"Eligible hostel staff member not found"})}
    const existing=await pool.query("SELECT * FROM conversations WHERE conversation_type=$1 AND parent_user_id=$2 AND student_user_id=$3 AND COALESCE(hostel_id,0)=COALESCE($4,0) AND COALESCE(staff_user_id,0)=COALESCE($5,0)",[type,req.user.id,studentId,hostelId,Number.isFinite(staffId)?staffId:null]);if(existing.rowCount)return res.json({conversation:existing.rows[0],existing:true});const r=await pool.query("INSERT INTO conversations (conversation_type,parent_user_id,student_user_id,hostel_id,staff_user_id) VALUES ($1,$2,$3,$4,$5) RETURNING *",[type,req.user.id,studentId,hostelId,type==='parent_staff'?staffId:null]);res.status(201).json({conversation:r.rows[0]});});
  app.get("/api/conversations",requireAuth,requireRole("parent","student","owner","warden"),async(req,res)=>{const r=await pool.query("SELECT c.* FROM conversations c WHERE c.parent_user_id=$1 OR c.student_user_id=$1 OR c.staff_user_id=$1 ORDER BY c.updated_at DESC",[req.user.id]);res.json({conversations:r.rows});});
  app.get("/api/conversations/:id/messages",requireAuth,async(req,res)=>{const c=await participant(Number(req.params.id),req.user);if(!c)return res.status(404).json({error:"Conversation not found"});const r=await pool.query("SELECT * FROM conversation_messages WHERE conversation_id=$1 ORDER BY created_at",[c.id]);res.json({messages:r.rows});});
  app.post("/api/conversations/:id/messages",requireAuth,async(req,res)=>{const c=await participant(Number(req.params.id),req.user),body=String(req.body.body||"").trim();if(!c)return res.status(404).json({error:"Conversation not found"});if(!body||body.length>4000)return res.status(400).json({error:"Message body must be 1 to 4000 characters"});const r=await pool.query("INSERT INTO conversation_messages (conversation_id,sender_user_id,body) VALUES ($1,$2,$3) RETURNING *",[c.id,req.user.id,body]);await pool.query("UPDATE conversations SET updated_at=NOW() WHERE id=$1",[c.id]);res.status(201).json({message:r.rows[0]});});
  app.post("/api/conversation-messages/:id/read",requireAuth,async(req,res)=>{const m=await pool.query("SELECT m.*,c.parent_user_id,c.student_user_id,c.staff_user_id FROM conversation_messages m JOIN conversations c ON c.id=m.conversation_id WHERE m.id=$1",[Number(req.params.id)]);if(!m.rowCount||![m.rows[0].parent_user_id,m.rows[0].student_user_id,m.rows[0].staff_user_id].includes(req.user.id))return res.status(404).json({error:"Message not found"});if(m.rows[0].sender_user_id===req.user.id)return res.status(409).json({error:"Sender cannot mark their own message read"});const r=await pool.query("UPDATE conversation_messages SET read_at=COALESCE(read_at,NOW()) WHERE id=$1 RETURNING *",[m.rows[0].id]);res.json({message:r.rows[0]});});
}
module.exports={registerMessagingRoutes};
