function registerVerificationRoutes({ app, pool, requireAuth, requireRole, isValidInt, ownerHasHostel }) {
  const active = ["draft","submitted","more_information_requested","inspection_scheduled","provisional","conditionally_approved"];
  async function ownApplication(ownerId, id) { return pool.query("SELECT * FROM hostel_registration_applications WHERE id=$1 AND owner_user_id=$2", [id, ownerId]); }
  async function event(client, applicationId, type, actorId, details={}) { await client.query("INSERT INTO hostel_verification_events (application_id,event_type,actor_user_id,details) VALUES ($1,$2,$3,$4::jsonb)", [applicationId,type,actorId,JSON.stringify(details)]); }

  app.post("/api/owner/verification-applications", requireAuth, requireRole("owner"), async (req,res)=>{
    const hostelId=Number(req.body.hostel_id); if(!isValidInt(hostelId)||!await ownerHasHostel(pool,req.user.id,hostelId)) return res.status(404).json({error:"Hostel not found"});
    const existing=await pool.query("SELECT id FROM hostel_registration_applications WHERE hostel_id=$1 AND status = ANY($2::varchar[])",[hostelId,active]); if(existing.rowCount) return res.status(409).json({error:"An active verification application already exists"});
    const result=await pool.query("INSERT INTO hostel_registration_applications (owner_user_id,hostel_id,submission_notes) VALUES ($1,$2,$3) RETURNING *",[req.user.id,hostelId,req.body.submission_notes||null]); await event(pool,result.rows[0].id,"created",req.user.id); res.status(201).json({application:result.rows[0]});
  });
  app.get("/api/owner/verification-applications", requireAuth, requireRole("owner"), async (req,res)=>{ const r=await pool.query("SELECT * FROM hostel_registration_applications WHERE owner_user_id=$1 ORDER BY created_at DESC",[req.user.id]);res.json({applications:r.rows}); });
  app.post("/api/owner/verification-applications/:id/documents", requireAuth, requireRole("owner"), async (req,res)=>{
    const id=Number(req.params.id),{document_type,storage_key,checksum}=req.body; const appResult=await ownApplication(req.user.id,id); if(!appResult.rowCount) return res.status(404).json({error:"Application not found"}); if(!["draft","more_information_requested"].includes(appResult.rows[0].status)||!document_type||!storage_key) return res.status(409).json({error:"Documents can be added only to a draft or information-requested application"});
    const r=await pool.query("INSERT INTO hostel_registration_documents (application_id,document_type,storage_key,checksum,submitted_by_user_id) VALUES ($1,$2,$3,$4,$5) RETURNING *",[id,document_type,storage_key,checksum||null,req.user.id]);await event(pool,id,"document_submitted",req.user.id,{document_id:r.rows[0].id,document_type});res.status(201).json({document:r.rows[0]});
  });
  app.post("/api/owner/verification-applications/:id/submit", requireAuth, requireRole("owner"), async (req,res)=>{
    const id=Number(req.params.id), a=await ownApplication(req.user.id,id);if(!a.rowCount)return res.status(404).json({error:"Application not found"});if(!["draft","more_information_requested"].includes(a.rows[0].status))return res.status(409).json({error:"Application cannot be submitted in its current state"});const docs=await pool.query("SELECT 1 FROM hostel_registration_documents WHERE application_id=$1",[id]);if(!docs.rowCount)return res.status(409).json({error:"At least one document is required before submission"});const r=await pool.query("UPDATE hostel_registration_applications SET status='submitted',submitted_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[id]);await event(pool,id,"submitted",req.user.id);res.json({application:r.rows[0]});
  });
  app.get("/api/admin/verification-applications", requireAuth, requireRole("admin"), async (req,res)=>{const r=await pool.query("SELECT a.*,u.name AS owner_name,u.email AS owner_email,h.name AS hostel_name FROM hostel_registration_applications a JOIN users u ON u.id=a.owner_user_id LEFT JOIN hostels h ON h.id=a.hostel_id WHERE ($1::varchar IS NULL OR a.status=$1) ORDER BY a.created_at DESC",[req.query.status||null]);res.json({applications:r.rows});});
  app.get("/api/admin/verification-applications/:id", requireAuth, requireRole("admin"), async (req,res)=>{const id=Number(req.params.id);const a=await pool.query("SELECT * FROM hostel_registration_applications WHERE id=$1",[id]);if(!a.rowCount)return res.status(404).json({error:"Application not found"});const [documents,events,inspections,conditions]=await Promise.all([pool.query("SELECT * FROM hostel_registration_documents WHERE application_id=$1",[id]),pool.query("SELECT * FROM hostel_verification_events WHERE application_id=$1 ORDER BY created_at",[id]),pool.query("SELECT * FROM hostel_inspections WHERE application_id=$1 ORDER BY scheduled_for",[id]),pool.query("SELECT * FROM hostel_approval_conditions WHERE application_id=$1 ORDER BY due_at",[id])]);res.json({application:a.rows[0],documents:documents.rows,events:events.rows,inspections:inspections.rows,conditions:conditions.rows});});
  app.post("/api/admin/verification-applications/:id/request-information", requireAuth, requireRole("admin"), async (req,res)=>{const id=Number(req.params.id),details=String(req.body.details||"").trim();if(!details)return res.status(400).json({error:"Request details are required"});const r=await pool.query("UPDATE hostel_registration_applications SET status='more_information_requested',updated_at=NOW() WHERE id=$1 AND status=ANY($2::varchar[]) RETURNING *",[id,active]);if(!r.rowCount)return res.status(404).json({error:"Active application not found"});await event(pool,id,"information_requested",req.user.id,{details});res.json({application:r.rows[0]});});
  app.post("/api/admin/verification-applications/:id/inspections", requireAuth, requireRole("admin"), async (req,res)=>{const id=Number(req.params.id),{priority,scheduled_for,assigned_to_user_id,scope=[]}=req.body;if(!["high","standard","low"].includes(priority)||Number.isNaN(Date.parse(scheduled_for)))return res.status(400).json({error:"Valid priority and scheduled_for are required"});const r=await pool.query("INSERT INTO hostel_inspections (application_id,priority,assigned_to_user_id,scheduled_for,scope,created_by_user_id) VALUES ($1,$2,$3,$4,$5::jsonb,$6) RETURNING *",[id,priority,assigned_to_user_id||null,scheduled_for,JSON.stringify(scope),req.user.id]);await pool.query("UPDATE hostel_registration_applications SET status='inspection_scheduled',updated_at=NOW() WHERE id=$1",[id]);await event(pool,id,"inspection_scheduled",req.user.id,{inspection_id:r.rows[0].id});res.status(201).json({inspection:r.rows[0]});});
  app.post("/api/admin/verification-applications/:id/conditions", requireAuth, requireRole("admin"), async (req,res)=>{const id=Number(req.params.id),{requirement,due_at}=req.body;if(!requirement||Number.isNaN(Date.parse(due_at)))return res.status(400).json({error:"requirement and due_at are required"});const r=await pool.query("INSERT INTO hostel_approval_conditions (application_id,requirement,due_at,created_by_user_id) VALUES ($1,$2,$3,$4) RETURNING *",[id,requirement,due_at,req.user.id]);await event(pool,id,"condition_added",req.user.id,{condition_id:r.rows[0].id});res.status(201).json({condition:r.rows[0]});});
  app.patch("/api/admin/verification-applications/:id/decision", requireAuth, requireRole("admin"), async (req,res)=>{const id=Number(req.params.id),status=String(req.body.status||""),reason=String(req.body.reason||"").trim();if(!["provisional","conditionally_approved","approved","rejected"].includes(status)||(status==="rejected"&&!reason))return res.status(400).json({error:"Valid decision status and rejection reason are required"});const c=await pool.connect();try{await c.query("BEGIN");const a=await c.query("SELECT * FROM hostel_registration_applications WHERE id=$1 FOR UPDATE",[id]);if(!a.rowCount){await c.query("ROLLBACK");return res.status(404).json({error:"Application not found"});}const r=await c.query("UPDATE hostel_registration_applications SET status=$1,decided_at=NOW(),decided_by_user_id=$2,reapplication_allowed=COALESCE($3,reapplication_allowed),updated_at=NOW() WHERE id=$4 RETURNING *",[status,req.user.id,req.body.reapplication_allowed??null,id]);if(a.rows[0].hostel_id)await c.query("UPDATE hostels SET verified=$1 WHERE id=$2",[status==="approved",a.rows[0].hostel_id]);await event(c,id,`decision_${status}`,req.user.id,{reason:reason||null});await c.query("COMMIT");res.json({application:r.rows[0]});}catch(e){await c.query("ROLLBACK");res.status(500).json({error:"Failed to decide application"});}finally{c.release();}});
}
module.exports={registerVerificationRoutes};
