// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAQ7j42oW0vLojSztC4osxzQ_UXts_1U',
    appId: '1:620915948190:web:0cc342d754d65ab738598f',
    messagingSenderId: '620915948190',
    projectId: 'staybuddy-c936b',
    authDomain: 'staybuddy-c936b.firebaseapp.com',
    storageBucket: 'staybuddy-c936b.firebasestorage.app',
    measurementId: 'G-Z6LVM57LHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPjRUA56bfydZIFekocVnPWCHfCjmnEU',
    appId: '1:620915948190:android:da141401e5978f9a38598f',
    messagingSenderId: '620915948190',
    projectId: 'staybuddy-c936b',
    storageBucket: 'staybuddy-c936b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4cDLyM12Zb8HnmcAc47VgH5DSIWOZ2E8',
    appId: '1:620915948190:ios:7bb962c5b59b298838598f',
    messagingSenderId: '620915948190',
    projectId: 'staybuddy-c936b',
    storageBucket: 'staybuddy-c936b.firebasestorage.app',
    iosBundleId: 'com.example.staybuddyStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4cDLyM12Zb8HnmcAc47VgH5DSIWOZ2E8',
    appId: '1:620915948190:ios:7bb962c5b59b298838598f',
    messagingSenderId: '620915948190',
    projectId: 'staybuddy-c936b',
    storageBucket: 'staybuddy-c936b.firebasestorage.app',
    iosBundleId: 'com.example.staybuddyStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAQ7j42oW0vLojSztC4osxzQ_UXts_1U',
    appId: '1:620915948190:web:9d91cf4edfbe93d538598f',
    messagingSenderId: '620915948190',
    projectId: 'staybuddy-c936b',
    authDomain: 'staybuddy-c936b.firebaseapp.com',
    storageBucket: 'staybuddy-c936b.firebasestorage.app',
    measurementId: 'G-L9CPKE2W2X',
  );
}
